name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkgUCDPWZIa6af90b7l3RUScLQA
          youtube_api_key: AIzaSyBLpGHEM39JInXeCYo2Ts2KD1kMHx6e__c
          max_videos: 12
          base_url: https://ytcards.demolab.com/
          card_width: 250
          
